config/routes.rb
Rails.application.routes.draw do

  root 'session#welcometo'

  resources :apprentices

  resources :masters

  resources :users

  resources :masters do
    collection do
      post 'search', to: 'masters#search'
    end
  end

  post 'signin', to: 'session#signin'
  post 'signup', to: 'session#signup'
  delete 'signout', to: 'session#signout'

end

app/models/master.rb
# == Schema Information
#
# Table name: masters
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  domain     :string(255)
#  city       :string(255)
#  state      :boolean
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Master < ActiveRecord::Base
  has_many :apprentices
  belongs_to :user

  scope :for_user, ->(user) { where(user: user) }

end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  before_action :set_master, only: [:show, :edit, :update, :destroy]

  # GET /masters
  # GET /masters.json
  def index
    @masters = Master.for_user(current_user)
  end

  # GET /masters/1
  # GET /masters/1.json
  def show

    def search
      @masters = Master.for_user(current_user)
        .where("title like ?", "%#{search_query}%"), "%#{params[:search_query]}%"
        render :template => 'masters/index'
    end

  end

  # GET /masters/new
  def new
    @master = Master.new
  end

  # GET /masters/1/edit
  def edit
  end

  # POST /masters
  # POST /masters.json
  def create
    @master = Master.new(master_params)
    @master.user = current_user

    respond_to do |format|
      if @master.save
        format.html { redirect_to @master, notice: 'Master was successfully created.' }
        format.json { render :show, status: :created, location: @master }
      else
        format.html { render :new }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masters/1
  # PATCH/PUT /masters/1.json
  def update
    respond_to do |format|
      if @master.update(master_params)
        format.html { redirect_to @master, notice: 'Master was successfully updated.' }
        format.json { render :show, status: :ok, location: @master }
      else
        format.html { render :edit }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1
  # DELETE /masters/1.json
  def destroy
    @master.destroy
    respond_to do |format|
      format.html { redirect_to masters_url, notice: 'Master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master
      @master = Master.for_user(current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def master_params
      params.require(:master).permit(:name, :domain, :city, :state)
    end
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/views/masters/_form.html.erb
<%= form_for(@master) do |f| %>
  <% if @master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@master.errors.count, "error") %> prohibited this master from being saved:</h2>

      <ul>
      <% @master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/masters/edit.html.erb
<h1>Editing master</h1>

<%= render 'form' %>

<%= link_to 'Show', @master %> |
<%= link_to 'Back', masters_path %>

app/views/masters/index.html.erb
<%= form_tag search_masters_path, class: 'form' do %>
    <%= text_field_tag "search_query", nil, placeholder: 'Search text' %>
    <%= submit_tag "Search", class: 'btn btn-sm' %>
<%end%>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Domain</th>
      <th>City</th>
      <th>User Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @masters.each do |master| %>
      <tr>
        <td><%= master.name %></td>
        <td><%= master.domain %></td>
        <td><%= master.city %></td>
        <td><%= master.user.name if master.user %></td>
        <td>
          <%= link_to master, class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-search"></span>
              Show
          <% end %>
        </td>
        <td>
          <%= link_to edit_master_path(master), class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
          <% end %>
        </td>
        <td>
          <%= link_to master, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
              <span class="glyphicon glyphicon-remove"></span>
              Destroy
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4><%= link_to 'New Master', new_master_path %></h4>

app/views/masters/new.html.erb
<h1>New master</h1>

<%= render 'form' %>

<%= link_to 'Back', masters_path %>

app/views/masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @master.name %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @master.domain %>
</p>

<p>
  <strong>City:</strong>
  <%= @master.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @master.state %>
</p>

<%= link_to 'Edit', edit_master_path(@master) %> |
<%= link_to 'Back', masters_path %>