config/routes.rb
Rails.application.routes.draw do

  root 'session#welcometo'

  resources :apprentices

  resources :masters

  resources :users

  resources :masters do
    collection do
      post 'search', to: 'masters#search'
    end
  end

  post 'signin', to: 'session#signin'
  post 'signup', to: 'session#signup'
  delete 'signout', to: 'session#signout'

end

app/models/apprentice.rb
# == Schema Information
#
# Table name: apprentices
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  city       :string(255)
#  master_id  :integer
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Apprentice < ActiveRecord::Base
  belongs_to :master
  belongs_to :user
end

app/controllers/apprentices_controller.rb
class ApprenticesController < ApplicationController
  before_action :set_apprentice, only: [:show, :edit, :update, :destroy]

  # GET /apprentices
  # GET /apprentices.json
  def index
    @apprentices = Apprentice.all
  end

  # GET /apprentices/1
  # GET /apprentices/1.json
  def show
  end

  # GET /apprentices/new
  def new
    @apprentice = Apprentice.new
  end

  # GET /apprentices/1/edit
  def edit
  end

  # POST /apprentices
  # POST /apprentices.json
  def create
    @apprentice = Apprentice.new(apprentice_params)

    respond_to do |format|
      if @apprentice.save
        format.html { redirect_to @apprentice, notice: 'Apprentice was successfully created.' }
        format.json { render :show, status: :created, location: @apprentice }
      else
        format.html { render :new }
        format.json { render json: @apprentice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apprentices/1
  # PATCH/PUT /apprentices/1.json
  def update
    respond_to do |format|
      if @apprentice.update(apprentice_params)
        format.html { redirect_to @apprentice, notice: 'Apprentice was successfully updated.' }
        format.json { render :show, status: :ok, location: @apprentice }
      else
        format.html { render :edit }
        format.json { render json: @apprentice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apprentices/1
  # DELETE /apprentices/1.json
  def destroy
    @apprentice.destroy
    respond_to do |format|
      format.html { redirect_to apprentices_url, notice: 'Apprentice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apprentice
      @apprentice = Apprentice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apprentice_params
      params.require(:apprentice).permit(:name, :city, :master_name, :master_id)
    end
end

app/helpers/apprentices_helper.rb
module ApprenticesHelper
end

app/views/apprentices/_form.html.erb
<%= form_for(@apprentice) do |f| %>
  <% if @apprentice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apprentice.errors.count, "error") %> prohibited this apprentice from being saved:</h2>

      <ul>
      <% @apprentice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label 'Master Name' %><br>
    <%= f.select :master_id, options_for_select(Master.all.collect{ |i| [i.name, i.id]})  %>

  </div>

  <div class="actions">
    <%= f.submit %>

  </div>

<%end%>

app/views/apprentices/edit.html.erb
<h1>Editing apprentice</h1>

<%= render 'form' %>

<%= link_to 'Show', @apprentice %> |
<%= link_to 'Back', apprentices_path %>

app/views/apprentices/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Master's<br> Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apprentices.each do |apprentice| %>
      <tr>
        <td><%= apprentice.name %></td>
        <td><%= apprentice.city %></td>
        <td><%= apprentice.master.name %></td>
        <td>
          <%= link_to apprentice, class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-search"></span>
              Show
          <% end %>
        </td>
        <td>
          <%= link_to edit_apprentice_path(apprentice), class: 'btn btn-default' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
          <% end %>
        </td>
        <td>
          <%= link_to apprentice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
              <span class="glyphicon glyphicon-remove"></span>
              Destroy
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4><%= link_to 'New Apprentice', new_apprentice_path %></h4>

app/views/apprentices/new.html.erb
<h1>New apprentice</h1>

<%= render 'form' %>

<%= link_to 'Back', apprentices_path %>

app/views/apprentices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @apprentice.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @apprentice.city %>
</p>

<p>
  <strong>Master name:</strong>
  <%= @apprentice.master.name %>
</p>


<%= link_to 'Edit', edit_apprentice_path(@apprentice) %> |
<%= link_to 'Back', apprentices_path %>