config/routes.rb
Rails.application.routes.draw do

  root 'session#welcometo'

  resources :apprentices

  resources :masters

  resources :users

  resources :masters do
    collection do
      post 'search', to: 'masters#search'
    end
  end

  post 'signin', to: 'session#signin'
  post 'signup', to: 'session#signup'
  delete 'signout', to: 'session#signout'

end

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>
<% if flash[:warning] %>
    <div class="alert alert-warning"><%= flash[:warning] %></div>
<% end %>

app/views/layouts/_footer.html.erb
<br>
<h4><%= link_to "Sign out", signout_path, method: :delete%></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApprenticeToMaster</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</head>
<body>


<%= render 'layouts/flash_messages' %>


<div class="row">
  <div class="col-md-12 text-center">
    <p><h1>Apprentice to Master</h1></p>

  </div>
</div>

<% if signed_in? %>
<ul class="nav nav-pills" role="tablist">
  <li role="presentation"><%= link_to 'Master List', masters_path %></li>
  <li role="presentation"><%= link_to 'Apprentice List', apprentices_path %></li>
  <% if current_user && current_user.admin? %>
  <li role="presentation"><%= link_to 'Users List', users_path %></li>
  <% end %>
</ul>
<% end %>


<%= yield %>

<% if signed_in? %>
<%= render 'layouts/footer' %>
<% end %>

</body>

</html>